<?php /* Smarty version Smarty-3.1.19, created on 2014-10-07 22:04:28
         compiled from "C:\xampp\htdocs\Reveria\admin\themes\default\css\overrides.css" */ ?>
<?php /*%%SmartyHeaderCode:29125434474cb842a2-55625328%%*/if(!defined('SMARTY_DIR')) exit('no direct access allowed');
$_valid = $_smarty_tpl->decodeProperties(array (
  'file_dependency' => 
  array (
    'c7d51bb68f2bc7d3afacde9ba0f06d30bbb443e8' => 
    array (
      0 => 'C:\\xampp\\htdocs\\Reveria\\admin\\themes\\default\\css\\overrides.css',
      1 => 1412712135,
      2 => 'file',
    ),
  ),
  'nocache_hash' => '29125434474cb842a2-55625328',
  'function' => 
  array (
  ),
  'has_nocache_code' => false,
  'version' => 'Smarty-3.1.19',
  'unifunc' => 'content_5434474cb87af2_67770969',
),false); /*/%%SmartyHeaderCode%%*/?>
<?php if ($_valid && !is_callable('content_5434474cb87af2_67770969')) {function content_5434474cb87af2_67770969($_smarty_tpl) {?>/* This stylesheet should be used to add your custom styles to the back-office without using the Sass sources. It will be loaded after all the default styles. 
You should NOT edit any other exisiting back-office CSS file manually: they are generated by the Sass preprocessor: http://www.sass-lang.com/ . */<?php }} ?>
