<?php
define('_DB_SERVER_', '127.0.0.1');
define('_DB_NAME_', 'riviera');
define('_DB_USER_', 'root');
define('_DB_PASSWD_', '');
define('_DB_PREFIX_', 'riv_');
define('_MYSQL_ENGINE_', 'InnoDB');
define('_PS_CACHING_SYSTEM_', 'CacheMemcache');
define('_PS_CACHE_ENABLED_', '0');
define('_MEDIA_SERVER_1_', '');
define('_MEDIA_SERVER_2_', '');
define('_MEDIA_SERVER_3_', '');
define('_COOKIE_KEY_', 't3htcwj7WUzbX0PUQOOvjysDMG27dexCIiDwmKfuSfe4ExIAJqL7zt47');
define('_COOKIE_IV_', 'ZDvPddWu');
define('_PS_CREATION_DATE_', '2014-10-13');
if (!defined('_PS_VERSION_'))
	define('_PS_VERSION_', '1.6.0.9');
define('_RIJNDAEL_KEY_', '3asukwEssz9FkNcyInoRrmsd1RMVovY8');
define('_RIJNDAEL_IV_', 'NQ+V4X2j32cF+8wl8N9CoQ==');
