<?php /* Smarty version Smarty-3.1.19, created on 2014-10-13 23:52:45
         compiled from "C:\xampp\htdocs\Riviera\admin\themes\default\css\overrides.css" */ ?>
<?php /*%%SmartyHeaderCode:24908543c49ad744988-50998475%%*/if(!defined('SMARTY_DIR')) exit('no direct access allowed');
$_valid = $_smarty_tpl->decodeProperties(array (
  'file_dependency' => 
  array (
    '00f2cf48bcd32729951416411ec6c85942d01511' => 
    array (
      0 => 'C:\\xampp\\htdocs\\Riviera\\admin\\themes\\default\\css\\overrides.css',
      1 => 1413236835,
      2 => 'file',
    ),
  ),
  'nocache_hash' => '24908543c49ad744988-50998475',
  'function' => 
  array (
  ),
  'has_nocache_code' => false,
  'version' => 'Smarty-3.1.19',
  'unifunc' => 'content_543c49ad747ed7_12435453',
),false); /*/%%SmartyHeaderCode%%*/?>
<?php if ($_valid && !is_callable('content_543c49ad747ed7_12435453')) {function content_543c49ad747ed7_12435453($_smarty_tpl) {?>/* This stylesheet should be used to add your custom styles to the back-office without using the Sass sources. It will be loaded after all the default styles. 
You should NOT edit any other exisiting back-office CSS file manually: they are generated by the Sass preprocessor: http://www.sass-lang.com/ . */<?php }} ?>
